# Generated by Django 5.2.14 on 2026-05-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
