# -*- coding: utf-8 -*-
"""training_feature.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ksWHWaI3TV0yZDKMCV96xq3jU7ujhuWD
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import librosa
import numpy as np
import pandas as pd
import joblib
import subprocess

def extract_audio_ffmpeg(video_path, audio_path="temp_audio.mp3"):
    command = [
        "ffmpeg",
        "-i", video_path,   # مسار الفيديو
        "-vn",              # تجاهل الفيديو
        "-acodec", "mp3",  # صيغة WAV
        "-ar", "44100",     # sample rate
        "-ac", "1",         # mono
        audio_path
    ]
    subprocess.run(command, stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
    return audio_path

def predict_scores_from_video_ffmpeg(video_path):
    model_path = r"/content/drive/MyDrive/xgboost_model.pkl"

    # استخراج الصوت
    audio_path = extract_audio_ffmpeg(video_path)

    # قراءة الصوت واستخراج MFCC
    y, sr = librosa.load(audio_path, sr=None)
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
    mfcc_mean = np.mean(mfcc, axis=1)

    X = pd.DataFrame([mfcc_mean])
    #X.columns = [f"mfcc_{i+1}" for i in range(X.shape[1])]

    model = joblib.load(model_path)
    y_pred = model.predict(X)

    results = {
        "speech_rate_score": y_pred[0][0],
        "energy_score": y_pred[0][1],
        "confidence_score": y_pred[0][2],
        "pitch_mean": y_pred[0][3],
        "pitch_std": y_pred[0][4],
    }


    os.remove(audio_path)

    return results

path=r"/content/drive/MyDrive/Sozy pleading.mp4"
audio_results=predict_scores_from_video_ffmpeg(path)
audio_results

!pip install --upgrade numba llvmlite

import joblib # أو pickle حسب أنت مسيفه بإيه

# التأكد من تحميل الملف الفعلي وليس مجرد المسار
models = joblib.load("/content/drive/MyDrive/all_xgb_models.pkl")

import cv2
import numpy as np
import pandas as pd
from xgboost import XGBClassifier


X_body = [
    "lm_0_y", "lm_1_y",
    "lm_11_x", "lm_12_x",
    "lm_23_z"
]

X_emotion = [
    "happy_mean", "sad_mean", "angry_mean",
    "dominant_happy_percent",
    "dominant_fear_percent",
    "dominant_neutral_percent"
]

X_hybrid = X_body + X_emotion


# ----------------------------------
# 3️⃣ Main Prediction Function
# ----------------------------------

def predict_video(video_path):

    cap = cv2.VideoCapture(video_path)

    body_data = []
    emotion_data = []

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # -------------------------
        # Dummy body features
        # -------------------------
        body_features = {
            "lm_0_y": np.random.rand(),
            "lm_1_y": np.random.rand(),
            "lm_11_x": np.random.rand(),
            "lm_12_x": np.random.rand(),
            "lm_23_z": np.random.rand()
        }
        body_data.append(body_features)

        # -------------------------
        # Dummy emotion features
        # -------------------------
        emotion_features = {
            "happy_mean": np.random.rand(),
            "sad_mean": np.random.rand(),
            "angry_mean": np.random.rand(),
            "dominant_happy_percent": np.random.rand(),
            "dominant_fear_percent": np.random.rand(),
            "dominant_neutral_percent": np.random.rand()
        }
        emotion_data.append(emotion_features)

    cap.release()

    if len(body_data) == 0 or len(emotion_data) == 0:
        print("Video empty or features missing!")
        return {}

    body_df = pd.DataFrame(body_data)
    emotion_df = pd.DataFrame(emotion_data)

    body_mean = body_df.mean().to_dict()
    emotion_mean = emotion_df.mean().to_dict()

    final_features = {**body_mean, **emotion_mean}
    final_df = pd.DataFrame([final_features])

    # ✅ تأكدي كل الأعمدة موجودة
    for col in X_hybrid:
        if col not in final_df.columns:
            final_df[col] = 0.0

    predictions = {}

    for label, model_data in models.items():
        model = model_data["model"]
        encoder = model_data["encoder"]

        if label in ["head_stability_label",
                     "posture_openness_label",
                     "body_stability_label",
                     "body_confidence_label"]:
            X_input = final_df[X_body]

        elif label in ["emotional_state_label",
                       "emotional_confidence_label"]:
            X_input = final_df[X_emotion]

        else:
            X_input = final_df[X_hybrid]

        pred_encoded = model.predict(X_input)[0]
        pred_label = encoder.inverse_transform([pred_encoded])[0]
        predictions[label] = pred_label

    return predictions

path=r"/content/drive/MyDrive/Sozy pleading.mp4"
body_results = predict_video(path)

print(body_results)

!pip install groq

from groq import Groq

client = Groq(
    api_key="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"
)

prompt = f"""
حلل أداء المتحدث بناءً على النتائج التالية:

تحليل الصوت:
- معدل الكلام: {audio_results['speech_rate_score']}
- الطاقة الصوتية: {audio_results['energy_score']}
- الثقة في الصوت: {audio_results['confidence_score']}
- متوسط طبقة الصوت: {audio_results['pitch_mean']}
- تذبذب طبقة الصوت: {audio_results['pitch_std']}

تحليل لغة الجسد:
- ثبات الرأس: {body_results['head_stability_label']}
- وضعية الجسم: {body_results['posture_openness_label']}
- استقرار الجسم: {body_results['body_stability_label']}
- ثقة لغة الجسد: {body_results['body_confidence_label']}

تحليل المشاعر:
- الحالة العاطفية: {body_results['emotional_state_label']}
- الثقة العاطفية: {body_results['emotional_confidence_label']}
- الثقة العامة: {body_results['overall_confidence_label']}
- مستوى التفاعل: {body_results['engagement_label']}

اكتب تقريرًا عربيًا احترافيًا ومنظمًا يوضح:
- شخصية المتحدث
- مستوى الثقة
- الحالة النفسية
- نقاط القوة
- نقاط الضعف
- نصائح للتحسين
"""

chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": prompt,
        }
    ],
    model="llama-3.3-70b-versatile"
)

report = chat_completion.choices[0].message.content

print(report)

