# Generated by Django 5.2.14 on 2026-06-17 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=255)),
                ('contract_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'نص'), ('number', 'رقم'), ('date', 'تاريخ')], default='text', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContractField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_fields', to='contracts.contract')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_fields', to='contracts.field')),
            ],
        ),
    ]
