# Generated by Django 5.2.14 on 2026-06-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contracthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'نص'), ('number', 'رقم'), ('date', 'تاريخ')], default='text', max_length=50),
        ),
    ]
