# Generated by Django 5.2.14 on 2026-06-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_field_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
